### ISSUE TITLE
Features missing from acme provider?

### ISSUE THREAD

**Issue by ringods** [ruben-janssens/pulumi-dynamic-acme#6]
Hello @ruben-janssens,

I bumped into this repository because it showed up in a Github search result.

I work for Pulumi and on the side, I maintain the [Pulumi ACME](https://www.pulumi.com/registry/packages/acme/) provider. Out of curiosity, I would like to know your reason to build the ACME provider as a dynamic resource provider. Is there anything missing from the regular provider?

Ringo

**Comment by ruben-janssens** [comment]
Hi @ringods,

The reason I made this is because the official provider does not support a step in between request and validation to create/provision a record for DNS validation. This was a requirement for us.

And also it was interesting to do a deep dive into ACME :)

- Ruben
